name: Daily Puzzle Uploader

on:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST daily
  workflow_dispatch:

jobs:
  post_puzzle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install firebase-admin requests google-cloud-firestore

      - name: Create Firebase credentials file
        # This step decodes the Base64 secret and writes it to the JSON file.
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 --decode > firebase_credentials.json

      - name: Debug: Print credentials file content
        # IMPORTANT: This will print your secret to the logs!
        # Only use this for debugging and remove it once the issue is resolved.
        # Ensure your GitHub Actions logs are private.
        run: cat firebase_credentials.json

      - name: Upload puzzle to Firestore
        run: python .github/scripts/upload_daily_puzzle.py firebase_credentials.json
