name: Daily Chess Puzzle Upload

on:
  schedule:
    - cron: "0 6 * * *"   # Run daily at 6 AM UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  upload-puzzles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install firebase-admin requests python-chess

      - name: Run uploader script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python scripts/upload_puzzle.py
