name: Upload Daily Puzzle

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install firebase-admin requests

      - name: Export Firebase credentials
        run: echo "FIREBASE_CREDENTIALS_B64=${{ secrets.FIREBASE_CREDENTIALS_B64 }}" >> $GITHUB_ENV

      - name: Upload Puzzle
        run: python upload_puzzle.py
        env:
          FIREBASE_CREDENTIALS_B64: ${{ secrets.FIREBASE_CREDENTIALS_B64 }}
